apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: github
spec:
  displayName: GitHub
  enabled: true
  description: GitHub Inc. is a web-based hosting service for version control using Git.
  logo: /plugins/plugin-oauth2/assets/static/github.svg
  website: https://github.com
  helpPage: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  authenticationUrl: /oauth2/authorization/github
  bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/github
  unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/github
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: plugin-oauth2-config
