apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: github
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitHub
  description: GitHub Inc. is an Internet hosting service for software development and version control using Git.
  logo: /plugins/plugin-oauth2/assets/static/github.svg
  website: https://github.com
  helpPage: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  authenticationUrl: /oauth2/authorization/github
  bindingUrl: /oauth2/authorization/github
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/github/disconnect
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-github-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitee
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Gitee
  description: Gitee is an online forge that allows software version control using Git and is intended primarily for the hosting of open source software.
  logo: /plugins/plugin-oauth2/assets/static/gitee.svg
  website: https://gitee.com
  authenticationUrl: /oauth2/authorization/gitee
  bindingUrl: /oauth2/authorization/gitee
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/gitee/disconnect
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitee-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitlab
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitLab
  description: GitLab Inc. is an open-core company that operates GitLab, a DevOps software package which can develop, secure, and operate software.
  logo: /plugins/plugin-oauth2/assets/static/gitlab.svg
  website: https://gitlab.com
  authenticationUrl: /oauth2/authorization/gitlab
  bindingUrl: /oauth2/authorization/gitlab
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/gitlab/disconnect
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitlab-config
